### ISSUE TITLE
lagoon-logging: end2end tests and ansible service broker create high amount of indexes

### ISSUE THREAD

**Issue by Schnitzel** [amazeeio/charts#7]
on our openshift clusters we have an end2end test, which tests the creation of a new project, deploys a pod and removes the namespace again. This runs every 15min and creates 24*4 namespaces every day, therefore 96 indexes for the container logs:

```
container-logs-e2e-1594921999-4f5dk34jlba7lmvmjnc2hslnum_bi-_-unknown_environmenttype-_-2020.07 
container-logs-e2e-1595660042-m45wplgchbg5jgioiabnaf36ya_bi-_-unknown_environmenttype-_-2020.07
container-logs-e2e-1595105636-vggrvpciebffvefnrowsuquz3q_bi-_-unknown_environmenttype-_-2020.07
```

the same is for the ansible servicebroker which creates new namespaces as well:

```
container-logs-lagoon-dbaas-mariadb-apb-prov-nqr5n_bi-_-unknown_environmenttype-_-2020.07
container-logs-lagoon-dbaas-mariadb-apb-prov-gsdxw_bi-_-unknown_environmenttype-_-2020.07
container-logs-lagoon-dbaas-mariadb-apb-depr-gsdxw_bi-_-unknown_environmenttype-_-2020.07
```

in lagoon we captured them here:
https://github.com/amazeeio/lagoon/blob/8128a4db750a61fcda62e6d5206be6c4865506e9/services/logs2logs-db/pipeline/router-application-logs.conf#L68-L72
https://github.com/amazeeio/lagoon/blob/8128a4db750a61fcda62e6d5206be6c4865506e9/services/logs-forwarder/.lagoon.single.yml#L194-L211

can we implement something similar in lagoon-logging again? It keeps our elasticsearch cluster small.

I'm aware that this is maybe just a special think for amazee.io related cluster and might not be something that would be good for every lagoon installation, maybe we can do a similar thing to `excludeNamespaces` from the loggingOperator also for the logs-dispatcher?

**Comment by smlx** [comment]
hi @Schnitzel I've pushed a PR that fixes this issue, but it's hard-coding those particular indices. Are you okay with that solution or do you think we really need the flexibility of making this configurable without doing a new chart version release?

**Comment by Schnitzel** [comment]
@smlx 
good question, I guess I more thought about a way to ignore specific namespaces all together, instead of consolidating them. but I your code is not as intrusive that I thought, so I think we can just ship with that one and close this :)

**Comment by smlx** [comment]
Well it is certainly going to be cleaner and easier to just not collect logs from those namespaces altogether. I didn't realise that was an option. Did you want to collect those logs at all?

**Comment by Schnitzel** [comment]
good question, I guess it would be bad to not keep the logs, never know if we actually need them or not. also both systems (e2e and ansible service broker) will eventually go away (k8s doesn't have them, so this is just an openshift thing).

to make this cleaner: maybe we could add a custom filtering capability via helm values? so we could inject them only in openshift clusters?
